// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lozuycmrpepatqgvxfos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvenV5Y21ycGVwYXRxZ3Z4Zm9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODA1NjUsImV4cCI6MjA3MDI1NjU2NX0.tA8rAI_-mugkCF3RynkDaD6dmAibPQNLcy2bfX9tnLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});